### ISSUE TITLE
Slow loading - Pictures

### ISSUE THREAD

**Issue by nififre** [Vulca/website#19]
On my computer, pages are loading quite slow especially pictures.
Are there in a web format ? (I know we could do that on Photoshop which will permit to load pages quite faster than now.)

**Comment by AlexandreRousselet** [comment]
For picture, I already took in consideration the weight of each of them. 
Before to upload them, I reduced the weight from 5-7mo sometime 😬 to less than 1mo for each of them.

For exemple, here is the size of some of them: 

**Home Page:** 
- Picture 1 : 422 KB
- Picture 2 : 737 KB

**Seminar :** 
- Family picture Seminar 1 : 647 KB
- Family picture Seminar 1 : 1 MB
- Family picture Seminar 3 : 287 KB 


**Residency:** 
- Header woman and man: 336 KB
- Thomas animating a workshop in Poznan: 463 KB 
- Peter in front of his laptop: 492 KB

**Pilot Project:** 
- Paulo presenting his report in Clt-Fd: 406 KB
- General Overview Report: 86 KB
- Future of work report : 86 KB

@nififre, what can I do to make it better than this ... because then I am afraid to lose quality...

**Comment by nififre** [comment]
I will have a look then.
Thank you for your answer.

**Comment by nicolasdb** [comment]
bon, I know it's been a long time. 
but this issue is not closed. 

Do you still have the problem? Loading is quite fine on my side of the world.
